drop table if exists measurement;
drop table if exists metric;

create table if not exists metric
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(1024),
    base_unit   VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS measurement
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statistic VARCHAR(50) NOT NULL,
    value     VARCHAR(50) NOT NULL,
    metric_id BIGINT REFERENCES metric (id) ON DELETE CASCADE
);